version: '3'

services:
  php:
    container_name: php-webserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: KG5rQWK^^u!pHbz3
      MYSQL_DATABASE: nombre_tienda
